### numpy ndarray 이해하기
array(어레이 행렬) 단위로 데이터 관리

In [1]:
import numpy as np
import pandas as pd

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
arr1.shape

(5,)

In [6]:
data2 = [[1,2,3,4,],
        [5,6,7,8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.shape

(2, 4)

괄호 안에 크기 반드시 입력하기

In [10]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# 데이터 타입 확인
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [17]:
arr =np.array([1,2,3,4,5], dtype=np.int64)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr.dtype

dtype('int64')

In [21]:
# 데이터형 변환
float_arr = arr.astype(np.float64)

In [22]:
float_arr.dtype

dtype('float64')

In [4]:
# numpy에서 사용 가능한 데이터형 정리 

pd.DataFrame({'데이터형': ['int8, int16, int32, int64', 'uint8, uint16, uint32, uint64', 'float16, float32, float64, float128', 'complex64, complex128, complex256', 'bool', 'object', 'string_','unicode_'],
              '데이터형 코드': ['i1, i2, i4, i8','u1, u2, u4, u8','f2, f4, f8, f16','c8, c16, c32','b','O','S','U'],
              '설명' : ["부호가 있는 [8, 16, 32, 64]비트 정수" ,"부호가 없는 [8, 16, 32, 64]비트 정수", "[16, 32, 64, 128]비트 실수", "[64, 128, 256]비트 복소수", "불리언 (True 또는 False)", "Python 오브젝트 형","문자열","유니코드 문자열"]})

데이터형          데이터형 코드  \
0            int8, int16, int32, int64   i1, i2, i4, i8   
1        uint8, uint16, uint32, uint64   u1, u2, u4, u8   
2  float16, float32, float64, float128  f2, f4, f8, f16   
3    complex64, complex128, complex256     c8, c16, c32   
4                                 bool                b   
5                               object                O   
6                              string_                S   
7                             unicode_                U   

                            설명  
0  부호가 있는 [8, 16, 32, 64]비트 정수  
1  부호가 없는 [8, 16, 32, 64]비트 정수  
2       [16, 32, 64, 128]비트 실수  
3         [64, 128, 256]비트 복소수  
4          불리언 (True 또는 False)  
5                Python 오브젝트 형  
6                          문자열  
7                     유니코드 문자열

In [23]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [25]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [27]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [26]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [28]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [29]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [30]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [31]:
arr1 / arr2

array([[ 0.14285714,  0.25      ,  0.33333333],
       [ 0.4       ,  0.45454545,  0.5       ]])

In [32]:
arr1 *2 

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [33]:
arr1 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [34]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [35]:
arr3 = np.array([1,2,3],dtype = np.int64 )

In [36]:
arr1 + arr3

array([[ 2.,  4.,  6.],
       [ 5.,  7.,  9.]])