### array indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [11]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

In [14]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [15]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [17]:
arr2d[3,2]

15

In [18]:
arr2d[:2,1:3] = 0

In [19]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
# 불리언 인덱싱
arr2d == 1

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [21]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])

In [22]:
 data = np.array([[ 0.57587275, -2.84040808,  0.70568712, -0.1836896 ],
                     [-0.59389702, -1.35370379,  2.28127544,  0.03784684],
                     [-0.28854954,  0.8904534 ,  0.18153112,  0.95281901],
                     [ 0.75912188, -1.88118767, -2.37445741, -0.5908499 ],
                     [ 1.7403012 ,  1.33138843,  1.20897442, -0.58004389],
                     [ 1.11585923,  1.02466538, -0.74409379, -1.55236176],
                     [-0.45921447,  2.53114818,  0.5029578 , -0.24088216]])

In [23]:
# 불리언어레이 : 마스크(mask)
names == "Charles"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [24]:
data[names == "Charles", : ]

array([[ 0.57587275, -2.84040808,  0.70568712, -0.1836896 ],
       [ 0.75912188, -1.88118767, -2.37445741, -0.5908499 ]])

In [25]:
data[(names == "Charles") | (names == "Kilho"),:]

array([[ 0.57587275, -2.84040808,  0.70568712, -0.1836896 ],
       [-0.59389702, -1.35370379,  2.28127544,  0.03784684],
       [ 0.75912188, -1.88118767, -2.37445741, -0.5908499 ],
       [ 1.11585923,  1.02466538, -0.74409379, -1.55236176],
       [-0.45921447,  2.53114818,  0.5029578 , -0.24088216]])

In [27]:
data[:,3] < 0

array([ True, False, False,  True,  True,  True,  True], dtype=bool)

In [28]:
data[data[:,3] < 0 ,: ] = 0

In [29]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.59389702, -1.35370379,  2.28127544,  0.03784684],
       [-0.28854954,  0.8904534 ,  0.18153112,  0.95281901],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])