### 각 성분에 적용되는 함수

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### numpy에서 한 개의 array의 각 성분에 적용되는 함수 정리
- sum :	전체 성분의 합을 계산
- mean	: 전체 성분의 평균을 계산
- std, var : 전체 성분의 표준편차, 분산을 계산
- min, max : 전체 성분의 최솟값, 최댓값을 계산
- argmin, argmax : 전체 성분의 최솟값, 최댓값이 위치한 인덱스를 반환
- cumsum :	맨 첫번째 성분부터 각 성분까지의 누적합을 계산 (0에서부터 계속 더해짐)
- cumprod :	맨 첫번째 성분부터 각 성분까지의 누적곱을 계산 (1에서부터 계속 곱해짐)


In [5]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [6]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
x

array([-1.03328049, -0.91578265, -0.52815551,  0.533653  ,  0.24484141,
       -0.8241444 , -0.10389141,  1.87114487])

In [9]:
y

array([-0.7655639 ,  0.55955162, -1.09193744, -0.01972723, -1.27664026,
       -0.17109501, -0.55942161, -2.30501008])

In [10]:
np.maximum(x,y)

array([-0.7655639 ,  0.55955162, -0.52815551,  0.533653  ,  0.24484141,
       -0.17109501, -0.10389141,  1.87114487])

##### numpy에서 두 개의 array의 각 성분에 적용되는 함수
 : add(+) , subtract(-) , multiply(*) , divide(/) , maximum(최댓값), minnimum(최솟값)

### numpy의 array에 적용되는 통계함수 정리
- sum	: 전체 성분의 합을 계산
- mean :	전체 성분의 평균을 계산
- std, var :	전체 성분의 표준편차, 분산을 계산
- min, max :	전체 성분의 최솟값, 최댓값을 계산
- argmin, argmax  :	전체 성분의 최솟값, 최댓값이 위치한 인덱스를 반환
- cumsum : 맨 첫번째 성분부터 각 성분까지의 누적합을 계산 (0에서부터 계속 더해짐)
- cumprod	 : 맨 첫번째 성분부터 각 성분까지의 누적곱을 계산 (1에서부터 계속 곱해짐)

In [11]:
arr = np.random.randn(5,4)

In [12]:
arr

array([[ 2.18798114,  0.18027113, -1.16572971,  0.11735981],
       [ 0.94453321,  0.68405979, -0.19684184, -2.98967298],
       [-0.95488777,  0.65304361,  2.36103622,  1.03596561],
       [ 0.2664075 ,  0.09843398,  1.68015446, -1.62396273],
       [ 0.42835086, -1.7742594 ,  1.24047333,  0.38413279]])

In [13]:
arr.sum()

3.5568490154783912

In [14]:
arr.mean()

0.17784245077391955

In [15]:
arr.sum(axis=0)

array([ 2.87238495, -0.15845089,  3.91909246, -3.07617751])

In [16]:
arr.sum(axis=1)

array([ 1.31988237, -1.55792182,  3.09515767,  0.42103321,  0.27869759])

In [17]:
arr > 0

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True]], dtype=bool)

In [18]:
(arr>0).sum()

14

In [19]:
arr= np.random.randn(8)

In [20]:
arr

array([ 1.73013552, -0.9042248 , -0.8788892 , -0.83904872,  1.13980334,
        1.78072299, -0.75345536, -0.35335505])

In [21]:
# 오름차순 정렬
np.sort(arr)

array([-0.9042248 , -0.8788892 , -0.83904872, -0.75345536, -0.35335505,
        1.13980334,  1.73013552,  1.78072299])

In [22]:
# 내림차순 정렬 [::-1]
np.sort(arr)[::-1]

array([ 1.78072299,  1.73013552,  1.13980334, -0.35335505, -0.75345536,
       -0.83904872, -0.8788892 , -0.9042248 ])

In [23]:
arr = np.random.randn(5,3)

In [24]:
arr

array([[-0.2842802 , -1.84933038,  0.8178164 ],
       [ 1.54663497, -0.95910873, -0.6302042 ],
       [-0.23363639, -0.13208588, -1.19290935],
       [ 0.76948428, -0.36597661,  0.9545039 ],
       [ 0.09454317,  0.10904961, -0.06498113]])

In [25]:
# 행 방향 오름차순 정렬
np.sort(arr,axis=0)

array([[-0.2842802 , -1.84933038, -1.19290935],
       [-0.23363639, -0.95910873, -0.6302042 ],
       [ 0.09454317, -0.36597661, -0.06498113],
       [ 0.76948428, -0.13208588,  0.8178164 ],
       [ 1.54663497,  0.10904961,  0.9545039 ]])

In [26]:
# 열 방향 오름차순 정렬
np.sort(arr,axis=1)

array([[-1.84933038, -0.2842802 ,  0.8178164 ],
       [-0.95910873, -0.6302042 ,  1.54663497],
       [-1.19290935, -0.23363639, -0.13208588],
       [-0.36597661,  0.76948428,  0.9545039 ],
       [-0.06498113,  0.09454317,  0.10904961]])

In [27]:
large_arr = np.random.randn(150)

In [30]:
large_arr[:10]

array([ 1.04887919,  1.79661873,  0.81305927, -1.33660933,  0.71683367,
       -0.12690835,  0.38033713, -1.23607516, -0.15015328, -2.08750437])

In [31]:
np.sort(large_arr)[::-1][:10]

array([ 2.95265099,  2.37989258,  2.3544648 ,  2.15395327,  1.99413408,
        1.80190332,  1.79661873,  1.78631269,  1.76137022,  1.69586323])

In [ ]:
# 긴 배열에서 상위 5%에 위치하는 값
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]